//! The playback queue.
//!
//! This module holds the queue's *shape*. The advancement algorithm — what plays
//! next given a repeat mode, a manual queue and a shuffle pool — arrives with the
//! queue service in M7, and the smart ordering in M12.

use std::collections::VecDeque;

use super::ids::{MediaFileId, PlaylistId, ProfileId, RadioSessionId};
use crate::{CoreError, Result};

/// What happens when the current track ends (PROJECT_MASTER 2.3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum RepeatMode {
    /// Stop once the queue is exhausted.
    #[default]
    Off,
    /// Restart the list from the beginning once exhausted.
    All,
    /// Repeat the current track, ignoring the queue entirely.
    One,
}

impl RepeatMode {
    /// The text form stored in profile settings.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Off => "off",
            Self::All => "all",
            Self::One => "one",
        }
    }

    /// Parses the stored text form.
    pub fn parse(text: &str) -> Result<Self> {
        match text {
            "off" => Ok(Self::Off),
            "all" => Ok(Self::All),
            "one" => Ok(Self::One),
            other => Err(CoreError::invalid(
                "repeat mode",
                format!("unknown mode {other:?}"),
            )),
        }
    }

    /// Cycles Off -> All -> One -> Off, which is the order the toolbar button
    /// steps through.
    pub const fn next(self) -> Self {
        match self {
            Self::Off => Self::All,
            Self::All => Self::One,
            Self::One => Self::Off,
        }
    }

    /// True when the queue must not advance past the current track.
    pub const fn holds_current_track(self) -> bool {
        matches!(self, Self::One)
    }
}

/// Where a queued entry came from.
///
/// This is what decides the transition style: radio and playlist entries are
/// gapless, everything else crossfades (PROJECT_MASTER 2.4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum QueueOrigin {
    /// Picked from the library, by the user or by shuffle.
    Library,
    /// Part of a playlist being played through.
    Playlist(PlaylistId),
    /// Generated by a radio session.
    Radio(RadioSessionId),
}

/// One queued track.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QueueEntry {
    /// The file to play.
    pub media_file_id: MediaFileId,
    /// Where it came from.
    pub origin: QueueOrigin,
}

/// A profile's playback queue.
///
/// Three lists rather than one cursor into a vector, because they behave
/// differently: `manual` is a strict-priority FIFO the user controls, `upcoming`
/// is refillable by shuffle or radio, and `history` is what previous-track walks
/// back through.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Queue {
    /// Owning profile.
    pub profile_id: ProfileId,
    /// Explicitly queued tracks. Always consumed before [`Self::upcoming`]
    /// (PROJECT_MASTER 2.3, 10.5).
    pub manual: VecDeque<QueueEntry>,
    /// The automatic continuation: the rest of a playlist, a shuffle pool, or a
    /// radio batch.
    pub upcoming: VecDeque<QueueEntry>,
    /// Recently played entries, most recent last.
    pub history: Vec<QueueEntry>,
    /// What is playing now, if anything.
    pub current: Option<QueueEntry>,
    /// Repeat behaviour.
    pub repeat: RepeatMode,
    /// Whether the automatic continuation is shuffled.
    pub shuffle: bool,
}

impl Queue {
    /// An empty queue for a profile.
    pub fn new(profile_id: ProfileId) -> Self {
        Self {
            profile_id,
            manual: VecDeque::new(),
            upcoming: VecDeque::new(),
            history: Vec::new(),
            current: None,
            repeat: RepeatMode::default(),
            shuffle: false,
        }
    }

    /// True when nothing is playing and nothing is waiting.
    pub fn is_empty(&self) -> bool {
        self.current.is_none() && self.manual.is_empty() && self.upcoming.is_empty()
    }

    /// How many tracks are waiting, excluding the current one.
    pub fn pending_len(&self) -> usize {
        self.manual.len() + self.upcoming.len()
    }

    /// The entry that would play next, without consuming it.
    ///
    /// Manual entries win over the automatic continuation; under
    /// [`RepeatMode::One`] the current track wins over both.
    pub fn peek_next(&self) -> Option<&QueueEntry> {
        if self.repeat.holds_current_track() && self.current.is_some() {
            return self.current.as_ref();
        }
        self.manual.front().or_else(|| self.upcoming.front())
    }

    /// True when the round being played is a list the queue is holding.
    ///
    /// A playlist puts its remaining tracks in [`Self::upcoming`], so the queue
    /// knows where that round begins and can start it again. Library playback
    /// puts nothing there: its round is the library itself, which is a set of
    /// rows only the service can read. Repeat all therefore means two different
    /// things, and this is which of them applies.
    fn holds_its_own_round(&self) -> bool {
        !matches!(
            self.current,
            Some(QueueEntry {
                origin: QueueOrigin::Library,
                ..
            })
        )
    }

    /// The entry [`Self::advance`] would move to, without moving to it.
    ///
    /// [`Self::peek_next`] answers the shorter question — what is queued — which
    /// is what a "next" button needs to know. This one also covers the rewind
    /// repeat all performs at the end of a list, because the track that follows
    /// the last one is a track that has to be decoded before the last one ends.
    ///
    /// `None` is not the same as "nothing follows": with nothing queued, what
    /// follows a library track is the next row of the library, and the queue
    /// has no rows.
    pub fn following(&self) -> Option<QueueEntry> {
        if self.repeat.holds_current_track() && self.current.is_some() {
            return self.current;
        }

        if let Some(next) = self.manual.front().or_else(|| self.upcoming.front()) {
            return Some(*next);
        }

        if self.repeat == RepeatMode::All && self.holds_its_own_round() {
            // What played first plays first again, and a list of one is still a
            // list: with no history to rewind, the current track follows itself.
            return self.history.first().copied().or(self.current);
        }

        None
    }

    /// Moves to the next entry and returns it, or `None` when there is nowhere
    /// left to go.
    ///
    /// This is the whole advancement rule of PROJECT_MASTER 2.3 in one place:
    /// repeat one holds, the manual queue outranks the continuation, and repeat
    /// all refills from what has already played rather than stopping.
    /// `seed` is used only for the refill: the domain has no entropy of its
    /// own, and a round that comes back shuffled needs some.
    pub fn advance(&mut self, seed: u64) -> Option<QueueEntry> {
        if self.repeat.holds_current_track() && self.current.is_some() {
            return self.current;
        }

        if self.manual.is_empty()
            && self.upcoming.is_empty()
            && self.repeat == RepeatMode::All
            && self.holds_its_own_round()
        {
            // Everything that has played goes back in front. In the order it
            // played, unless shuffle is on — a second round in the first
            // round's order is the one thing shuffle exists to prevent, and it
            // was doing exactly that (`MASTER_ISSUES` 94). The track that is
            // ending is not among them yet: it is pushed below, and so leads
            // the round after this one.
            let mut round = std::mem::take(&mut self.history);
            if self.shuffle {
                crate::domain::policies::shuffle_policy::shuffle(&mut round, seed);
            }
            self.upcoming = round.into();

            // A single track is still a list. With nothing else to rewind to,
            // repeat all means play it again.
            if self.upcoming.is_empty() {
                return self.current;
            }
        }

        let next = self
            .manual
            .pop_front()
            .or_else(|| self.upcoming.pop_front());

        // A track that ran out is history whether or not anything follows it.
        if let Some(finished) = self.current.take() {
            self.history.push(finished);
        }
        self.current = next;
        next
    }

    /// Moves back to the previously played entry and returns it.
    ///
    /// The track being left goes to the front of the continuation rather than
    /// into the manual queue: it is not something the listener asked for by
    /// name, and the manual queue is.
    pub fn go_back(&mut self) -> Option<QueueEntry> {
        let previous = self.history.pop()?;
        if let Some(leaving) = self.current.take() {
            self.upcoming.push_front(leaving);
        }
        self.current = Some(previous);
        Some(previous)
    }

    /// Puts an entry at the end of the manual queue, to play before the
    /// continuation resumes.
    pub fn enqueue(&mut self, entry: QueueEntry) {
        self.manual.push_back(entry);
    }

    /// Replaces the continuation and starts on `entry`.
    ///
    /// The manual queue survives: it is the listener's own list, and choosing
    /// something else to play is not a reason to discard it.
    pub fn start(&mut self, entry: QueueEntry, continuation: Vec<QueueEntry>) {
        self.upcoming = continuation.into();
        self.move_to(entry);
    }

    /// Moves to an entry that was never waiting in either lane.
    ///
    /// What the library plays next is not held anywhere — it is simply the row
    /// after this one — so there is nothing to pop, only a track to leave
    /// behind.
    pub fn move_to(&mut self, entry: QueueEntry) {
        if let Some(leaving) = self.current.take() {
            self.history.push(leaving);
        }
        self.current = Some(entry);
    }
}

#[cfg(test)]
mod tests {
    /// One seed for every test here. What a shuffle *does* is tested in
    /// `shuffle_policy`; what these tests are about is which lane a track
    /// comes from, and that answer must not depend on a throw of the dice.
    const SEED: u64 = 7;

    #[test]
    fn a_second_round_under_shuffle_is_not_the_first_round_again() {
        // A playlist, because a library track continues by itself: repeat all
        // over the library means the next row, not the round just played, and
        // `holds_its_own_round` is where that is decided.
        let list = QueueOrigin::Playlist(PlaylistId::new());
        let played: Vec<QueueEntry> = (0..8).map(|_| entry(list)).collect();

        // The state at the end of a list: everything has played, repeat all is
        // on, and shuffle is on. What comes back is the whole round.
        let round = |seed: u64| -> Vec<QueueEntry> {
            let mut queue = Queue::new(ProfileId::new());
            queue.repeat = RepeatMode::All;
            queue.shuffle = true;
            queue.history = played.clone();
            queue.current = Some(entry(list));

            // `advance` refills and then takes the first of the refill, so
            // the round is what it moved to followed by what is left waiting.
            let moved_to = queue.advance(seed);
            moved_to
                .into_iter()
                .chain(queue.upcoming.iter().copied())
                .collect()
        };

        let first = round(1);
        assert_eq!(first.len(), played.len(), "the round comes back whole");
        assert!(
            first.iter().all(|track| played.contains(track)),
            "and it is the same tracks"
        );

        // Six seeds, because a shuffle is allowed to return the order it was
        // given and a test that fails one run in forty thousand is still a
        // test that fails. What is asserted is that the order can change at
        // all — in play order it never could.
        assert!(
            (1..=6).any(|seed| round(seed) != played),
            "the second round replayed the first round's order"
        );
    }

    use super::{MediaFileId, Queue, QueueEntry, QueueOrigin, RepeatMode};
    use crate::domain::ids::{PlaylistId, ProfileId};

    fn entry(origin: QueueOrigin) -> QueueEntry {
        QueueEntry {
            media_file_id: MediaFileId::new(),
            origin,
        }
    }

    #[test]
    fn repeat_button_cycles_back_to_off() {
        let mut mode = RepeatMode::Off;
        mode = mode.next();
        assert_eq!(mode, RepeatMode::All);
        mode = mode.next();
        assert_eq!(mode, RepeatMode::One);
        mode = mode.next();
        assert_eq!(mode, RepeatMode::Off);
    }

    #[test]
    fn manual_entries_outrank_the_automatic_continuation() {
        let mut queue = Queue::new(ProfileId::new());
        let automatic = entry(QueueOrigin::Playlist(PlaylistId::new()));
        let manual = entry(QueueOrigin::Library);
        queue.upcoming.push_back(automatic);
        queue.manual.push_back(manual);

        assert_eq!(queue.peek_next(), Some(&manual));
    }

    #[test]
    fn repeat_one_ignores_the_queue() {
        let mut queue = Queue::new(ProfileId::new());
        let current = entry(QueueOrigin::Library);
        queue.current = Some(current);
        queue.manual.push_back(entry(QueueOrigin::Library));
        queue.repeat = RepeatMode::One;

        assert_eq!(
            queue.peek_next(),
            Some(&current),
            "repeat one must not consume the manual queue"
        );
    }

    #[test]
    fn advancing_consumes_the_manual_queue_first_and_remembers_what_played() {
        let mut queue = Queue::new(ProfileId::new());
        let first = entry(QueueOrigin::Library);
        let manual = entry(QueueOrigin::Library);
        let automatic = entry(QueueOrigin::Library);

        queue.start(first, vec![automatic]);
        queue.enqueue(manual);

        assert_eq!(queue.advance(SEED), Some(manual));
        assert_eq!(queue.history, vec![first]);
        assert_eq!(queue.advance(SEED), Some(automatic));
        assert_eq!(queue.advance(SEED), None, "repeat off stops at the end");
        assert_eq!(queue.current, None);
    }

    #[test]
    fn repeat_all_starts_the_list_again_in_the_order_it_played() {
        let mut queue = Queue::new(ProfileId::new());
        let list = QueueOrigin::Playlist(PlaylistId::new());
        let (a, b, c) = (entry(list), entry(list), entry(list));
        queue.repeat = RepeatMode::All;
        queue.start(a, vec![b, c]);

        assert_eq!(queue.advance(SEED), Some(b));
        assert_eq!(queue.advance(SEED), Some(c));
        assert_eq!(queue.advance(SEED), Some(a), "round two");
        assert_eq!(queue.advance(SEED), Some(b));
        assert_eq!(queue.advance(SEED), Some(c));
    }

    #[test]
    fn repeat_all_with_one_track_plays_it_again() {
        let mut queue = Queue::new(ProfileId::new());
        let only = entry(QueueOrigin::Playlist(PlaylistId::new()));
        queue.repeat = RepeatMode::All;
        queue.start(only, Vec::new());

        assert_eq!(queue.advance(SEED), Some(only));
        assert!(queue.history.is_empty(), "it never left");
    }

    #[test]
    fn a_library_round_is_never_refilled_from_what_has_played() {
        let mut queue = Queue::new(ProfileId::new());
        let (a, b) = (entry(QueueOrigin::Library), entry(QueueOrigin::Library));
        queue.repeat = RepeatMode::All;
        queue.start(a, vec![b]);
        assert_eq!(queue.advance(SEED), Some(b));

        // Repeat all still means "begin the round again" — but the round is the
        // library, and putting what has played back in front would fill the
        // queue with tracks nobody queued.
        assert_eq!(queue.following(), None, "the service asks the library");
        assert_eq!(queue.advance(SEED), None);
        assert!(queue.upcoming.is_empty(), "nothing was put back in front");
    }

    #[test]
    fn what_follows_is_what_advancing_would_reach() {
        let mut queue = Queue::new(ProfileId::new());
        let list = QueueOrigin::Playlist(PlaylistId::new());
        let (a, b, c) = (entry(list), entry(list), entry(list));
        queue.start(a, vec![b, c]);

        assert_eq!(queue.following(), Some(b));
        assert_eq!(queue.following(), queue.peek_next().copied());

        // On the last track of a repeating list the two part company: nothing
        // is queued, so `peek_next` says there is nothing — and the track that
        // has to be decoded before this one ends is the first of the round to
        // come.
        queue.repeat = RepeatMode::All;
        queue.advance(SEED);
        queue.advance(SEED);
        assert_eq!(queue.peek_next(), None);
        assert_eq!(queue.following(), Some(a), "the list starts again");

        queue.repeat = RepeatMode::One;
        assert_eq!(queue.following(), Some(c), "and repeat one holds");
    }

    #[test]
    fn repeat_one_holds_the_track_without_touching_the_queue() {
        let mut queue = Queue::new(ProfileId::new());
        let current = entry(QueueOrigin::Library);
        let waiting = entry(QueueOrigin::Library);
        queue.start(current, vec![waiting]);
        queue.repeat = RepeatMode::One;

        assert_eq!(queue.advance(SEED), Some(current));
        assert_eq!(queue.upcoming.front(), Some(&waiting));
    }

    #[test]
    fn going_back_replays_the_previous_track_and_keeps_the_current_one_next() {
        let mut queue = Queue::new(ProfileId::new());
        let (a, b) = (entry(QueueOrigin::Library), entry(QueueOrigin::Library));
        queue.start(a, vec![b]);
        assert_eq!(queue.advance(SEED), Some(b));

        assert_eq!(queue.go_back(), Some(a));
        assert_eq!(queue.current, Some(a));
        assert_eq!(queue.upcoming.front(), Some(&b));
        assert_eq!(queue.go_back(), None, "nothing played before it");
    }

    #[test]
    fn emptiness_accounts_for_the_current_track() {
        let mut queue = Queue::new(ProfileId::new());
        assert!(queue.is_empty());
        assert_eq!(queue.pending_len(), 0);

        queue.current = Some(entry(QueueOrigin::Library));
        assert!(!queue.is_empty());
        assert_eq!(queue.pending_len(), 0, "the current track is not pending");
    }
}
