//! The playback queue.
//!
//! This module holds the queue's *shape*. The advancement algorithm — what plays
//! next given a repeat mode, a manual queue and a shuffle pool — arrives with the
//! queue service in M7, and the smart ordering in M12.

use std::collections::VecDeque;

use super::ids::{MediaFileId, PlaylistId, ProfileId, RadioSessionId};
use crate::{CoreError, Result};

/// What happens when the current track ends (PROJECT_MASTER 2.3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum RepeatMode {
    /// Stop once the queue is exhausted.
    #[default]
    Off,
    /// Restart the list from the beginning once exhausted.
    All,
    /// Repeat the current track, ignoring the queue entirely.
    One,
}

impl RepeatMode {
    /// The text form stored in profile settings.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Off => "off",
            Self::All => "all",
            Self::One => "one",
        }
    }

    /// Parses the stored text form.
    pub fn parse(text: &str) -> Result<Self> {
        match text {
            "off" => Ok(Self::Off),
            "all" => Ok(Self::All),
            "one" => Ok(Self::One),
            other => Err(CoreError::invalid(
                "repeat mode",
                format!("unknown mode {other:?}"),
            )),
        }
    }

    /// Cycles Off -> All -> One -> Off, which is the order the toolbar button
    /// steps through.
    pub const fn next(self) -> Self {
        match self {
            Self::Off => Self::All,
            Self::All => Self::One,
            Self::One => Self::Off,
        }
    }

    /// True when the queue must not advance past the current track.
    pub const fn holds_current_track(self) -> bool {
        matches!(self, Self::One)
    }
}

/// Where a queued entry came from.
///
/// This is what decides the transition style: radio and playlist entries are
/// gapless, everything else crossfades (PROJECT_MASTER 2.4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum QueueOrigin {
    /// Picked from the library, by the user or by shuffle.
    Library,
    /// Part of a playlist being played through.
    Playlist(PlaylistId),
    /// Generated by a radio session.
    Radio(RadioSessionId),
}

/// One queued track.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QueueEntry {
    /// The file to play.
    pub media_file_id: MediaFileId,
    /// Where it came from.
    pub origin: QueueOrigin,
}

/// A profile's playback queue.
///
/// Three lists rather than one cursor into a vector, because they behave
/// differently: `manual` is a strict-priority FIFO the user controls, `upcoming`
/// is refillable by shuffle or radio, and `history` is what previous-track walks
/// back through.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Queue {
    /// Owning profile.
    pub profile_id: ProfileId,
    /// Explicitly queued tracks. Always consumed before [`Self::upcoming`]
    /// (PROJECT_MASTER 2.3, 10.5).
    pub manual: VecDeque<QueueEntry>,
    /// The automatic continuation: the rest of a playlist, a shuffle pool, or a
    /// radio batch.
    pub upcoming: VecDeque<QueueEntry>,
    /// Recently played entries, most recent last.
    pub history: Vec<QueueEntry>,
    /// What is playing now, if anything.
    pub current: Option<QueueEntry>,
    /// Repeat behaviour.
    pub repeat: RepeatMode,
    /// Whether the automatic continuation is shuffled.
    pub shuffle: bool,
}

impl Queue {
    /// An empty queue for a profile.
    pub fn new(profile_id: ProfileId) -> Self {
        Self {
            profile_id,
            manual: VecDeque::new(),
            upcoming: VecDeque::new(),
            history: Vec::new(),
            current: None,
            repeat: RepeatMode::default(),
            shuffle: false,
        }
    }

    /// True when nothing is playing and nothing is waiting.
    pub fn is_empty(&self) -> bool {
        self.current.is_none() && self.manual.is_empty() && self.upcoming.is_empty()
    }

    /// How many tracks are waiting, excluding the current one.
    pub fn pending_len(&self) -> usize {
        self.manual.len() + self.upcoming.len()
    }

    /// The entry that would play next, without consuming it.
    ///
    /// Manual entries win over the automatic continuation; under
    /// [`RepeatMode::One`] the current track wins over both.
    pub fn peek_next(&self) -> Option<&QueueEntry> {
        if self.repeat.holds_current_track() && self.current.is_some() {
            return self.current.as_ref();
        }
        self.manual.front().or_else(|| self.upcoming.front())
    }
}

#[cfg(test)]
mod tests {
    use super::{MediaFileId, Queue, QueueEntry, QueueOrigin, RepeatMode};
    use crate::domain::ids::{PlaylistId, ProfileId};

    fn entry(origin: QueueOrigin) -> QueueEntry {
        QueueEntry {
            media_file_id: MediaFileId::new(),
            origin,
        }
    }

    #[test]
    fn repeat_button_cycles_back_to_off() {
        let mut mode = RepeatMode::Off;
        mode = mode.next();
        assert_eq!(mode, RepeatMode::All);
        mode = mode.next();
        assert_eq!(mode, RepeatMode::One);
        mode = mode.next();
        assert_eq!(mode, RepeatMode::Off);
    }

    #[test]
    fn manual_entries_outrank_the_automatic_continuation() {
        let mut queue = Queue::new(ProfileId::new());
        let automatic = entry(QueueOrigin::Playlist(PlaylistId::new()));
        let manual = entry(QueueOrigin::Library);
        queue.upcoming.push_back(automatic);
        queue.manual.push_back(manual);

        assert_eq!(queue.peek_next(), Some(&manual));
    }

    #[test]
    fn repeat_one_ignores_the_queue() {
        let mut queue = Queue::new(ProfileId::new());
        let current = entry(QueueOrigin::Library);
        queue.current = Some(current);
        queue.manual.push_back(entry(QueueOrigin::Library));
        queue.repeat = RepeatMode::One;

        assert_eq!(
            queue.peek_next(),
            Some(&current),
            "repeat one must not consume the manual queue"
        );
    }

    #[test]
    fn emptiness_accounts_for_the_current_track() {
        let mut queue = Queue::new(ProfileId::new());
        assert!(queue.is_empty());
        assert_eq!(queue.pending_len(), 0);

        queue.current = Some(entry(QueueOrigin::Library));
        assert!(!queue.is_empty());
        assert_eq!(queue.pending_len(), 0, "the current track is not pending");
    }
}
